((emoji--command-Emoji nil)
 (emoji--command-Emoji\ >\ Animals\ &\ Nature nil)
 (emoji--command-Emoji\ >\ Animals\ &\ Nature\ >\ animal nil)
 (emoji--command-Emoji\ >\ Animals\ &\ Nature\ >\ animal\ >\ mammal nil)
 (emoji--command-Emoji\ >\ Flags nil)
 (emoji--command-Emoji\ >\ Flags\ >\ flag nil)
 (emoji--command-Emoji\ >\ Flags\ >\ subdivision-flag nil)
 (emoji--command-Emoji\ >\ Smileys nil)
 (emoji--command-Emoji\ >\ Smileys\ >\ glasses nil)
 (emoji--command-Emoji\ >\ Smileys\ >\ negative nil)
 (emoji--command-Emoji\ >\ Smileys\ >\ neutral-skeptical nil)
 (emoji--command-Emoji\ >\ Smileys\ >\ smiling nil)
 (emoji--command-Emoji\ >\ Smileys\ >\ unwell nil)
 (magit-blame
  ("-w"))
 (magit-branch nil)
 (magit-commit nil)
 (magit-ediff nil)
 (magit-fetch nil)
 (magit-gitignore nil)
 (magit-log
  ("-n256" "--graph" "--decorate"))
 (magit-merge nil)
 (magit-pull nil)
 (magit-push nil
             ("--force-with-lease"))
 (magit-rebase nil
               ("--autostash"))
 (magit-remote
  ("-f"))
 (magit-remote.<remote>.*url "git@github.com:smandy/implot.git" "git@github.com:epezent/implot.git" "git@github.com:smandy/aurora.git" "git@github.com:smandy/zenith.git")
 (magit-run nil)
 (magit-tag nil))
