;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        c-electric-brace
        c-electric-colon
        c-electric-semi&comma
        c-electric-slash
        clang-format-buffer
        end-of-buffer
        fill-paragraph
        helm-M-x
        indent-for-tab-command
        kill-region
        org-beginning-of-line
        org-ctrl-c-minus
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-metaup
        org-self-insert-command
        org-yank
        wdired-finish-edit
        yas-abort-snippet
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-lt-gt
        c-electric-paren
        goto-line
        markdown-outdent-or-delete
        mouse-appearance-menu
        mouse-buffer-menu
        mouse-set-region
        ))
