;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        clang-format-buffer
        indent-for-tab-command
        kill-region
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-buffer-menu
        mouse-set-region
        ))
