;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        clang-format-buffer
        indent-for-tab-command
        kill-region
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        org-yank
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-lt-gt
        c-electric-paren
        goto-line
        mouse-appearance-menu
        mouse-buffer-menu
        mouse-set-region
        ))
