(setq tags-hash #s(hash-table test equal size 1000 data ("1" "Account"
                                                        "159" "AccruedInterestAmt"
                                                        "158" "AccruedInterestRate"
                                                        "334" "Adjustment"
                                                        "2" "AdvId"
                                                        "3" "AdvRefID"
                                                        "4" "AdvSide"
                                                        "5" "AdvTransType"
                                                        "266" "AggregatedBook"
                                                        "79" "AllocAccount"
                                                        "153" "AllocAvgPx"
                                                        "209" "AllocHandlInst"
                                                        "70" "AllocID"
                                                        "196" "AllocLinkID"
                                                        "197" "AllocLinkType"
                                                        "154" "AllocNetMoney"
                                                        "366" "AllocPrice"
                                                        "88" "AllocRejCode"
                                                        "80" "AllocShares"
                                                        "87" "AllocStatus"
                                                        "161" "AllocText"
                                                        "71" "AllocTransType"
                                                        "74" "AvgPrxPrecision"
                                                        "6" "AvgPx"
                                                        "419" "BasisPxType"
                                                        "7" "BeginSeqNo"
                                                        "8" "BeginString"
                                                        "219" "Benchmark"
                                                        "400" "BidDescriptor"
                                                        "399" "BidDescriptorType"
                                                        "189" "BidForwardPoints"
                                                        "390" "BidID"
                                                        "132" "BidPx"
                                                        "374" "BidRequestTransType"
                                                        "134" "BidSize"
                                                        "188" "BidSpotRate"
                                                        "394" "BidType"
                                                        "9" "BodyLength"
                                                        "92" "BrokerOfCredit"
                                                        "380" "BusinessRejectReason"
                                                        "379" "BusinessRejectRefID"
                                                        "330" "BuyVolume"
                                                        "152" "CashOrderQty"
                                                        "185" "CashSettlAgentAcctName"
                                                        "184" "CashSettlAgentAcctNum"
                                                        "183" "CashSettlAgentCode"
                                                        "186" "CashSettlAgentContactName"
                                                        "187" "CashSettlAgentContactPhone"
                                                        "182" "CashSettlAgentName"
                                                        "10" "CheckSum"
                                                        "440" "ClearingAccount"
                                                        "439" "ClearingFirm"
                                                        "391" "ClientBidID"
                                                        "109" "ClientID"
                                                        "11" "ClOrdID"
                                                        "12" "Commission"
                                                        "13" "CommType"
                                                        "376" "ComplianceID"
                                                        "375" "ContraBroker"
                                                        "231" "ContractMultiplier"
                                                        "437" "ContraTradeQty"
                                                        "337" "ContraTrader"
                                                        "438" "ContraTradeTime"
                                                        "292" "CorporateAction"
                                                        "421" "Country"
                                                        "223" "CouponRate"
                                                        "203" "CoveredOrUncovered"
                                                        "413" "CrossPercent"
                                                        "14" "CumQty"
                                                        "15" "Currency"
                                                        "204" "CustomerOrFirm"
                                                        "84" "CxlQty"
                                                        "102" "CxlRejReason"
                                                        "434" "CxlRejResponseTo"
                                                        "125" "CxlType"
                                                        "426" "DayAvgPx"
                                                        "425" "DayCumQty"
                                                        "424" "DayOrderQty"
                                                        "293" "DefBidSize"
                                                        "294" "DefOfferSize"
                                                        "285" "DeleteReason"
                                                        "128" "DeliverToCompID"
                                                        "145" "DeliverToLocationID"
                                                        "129" "DeliverToSubID"
                                                        "284" "DeskID"
                                                        "388" "DiscretionInst"
                                                        "389" "DiscretionOffset"
                                                        "127" "DKReason"
                                                        "86" "DlvyInst"
                                                        "329" "DueToRelated"
                                                        "168" "EffectiveTime"
                                                        "405" "EFPTrackingError"
                                                        "164" "EmailThreadID"
                                                        "94" "EmailType"
                                                        "361" "EncodedAllocText"
                                                        "360" "EncodedAllocTextLen"
                                                        "359" "EncodedHeadline"
                                                        "358" "EncodedHeadlineLen"
                                                        "349" "EncodedIssuer"
                                                        "348" "EncodedIssuerLen"
                                                        "353" "EncodedListExecInst"
                                                        "352" "EncodedListExecInstLen"
                                                        "446" "EncodedListStatusText"
                                                        "445" "EncodedListStatusTextLen"
                                                        "351" "EncodedSecurityDesc"
                                                        "350" "EncodedSecurityDescLen"
                                                        "357" "EncodedSubject"
                                                        "356" "EncodedSubjectLen"
                                                        "355" "EncodedText"
                                                        "354" "EncodedTextLen"
                                                        "363" "EncodedUnderlyingIssuer"
                                                        "362" "EncodedUnderlyingIssuerLen"
                                                        "365" "EncodedUnderlyingSecurityDesc"
                                                        "364" "EncodedUnderlyingSecurityDescLen"
                                                        "98" "EncryptMethod"
                                                        "16" "EndSeqNo"
                                                        "411" "ExchangeForPhysical"
                                                        "100" "ExDestination"
                                                        "76" "ExecBroker"
                                                        "17" "ExecID"
                                                        "18" "ExecInst"
                                                        "19" "ExecRefID"
                                                        "378" "ExecRestatementReason"
                                                        "20" "ExecTransType"
                                                        "150" "ExecType"
                                                        "432" "ExpireDate"
                                                        "126" "ExpireTime"
                                                        "406" "FairValue"
                                                        "291" "FinancialStatus"
                                                        "121" "ForexReq"
                                                        "64" "FutSettDate"
                                                        "193" "FutSettDate2"
                                                        "123" "GapFillFlag"
                                                        "381" "GrossTradeAmt"
                                                        "427" "GTBookingInst"
                                                        "327" "HaltReason"
                                                        "21" "HandlInst"
                                                        "148" "Headline"
                                                        "108" "HeartBtInt"
                                                        "332" "HighPx"
                                                        "22" "IDSource"
                                                        "416" "IncTaxInd"
                                                        "328" "InViewOfCommon"
                                                        "23" "IOIid"
                                                        "130" "IOINaturalFlag"
                                                        "24" "IOIOthSvc"
                                                        "25" "IOIQltyInd"
                                                        "104" "IOIQualifier"
                                                        "26" "IOIRefID"
                                                        "27" "IOIShares"
                                                        "28" "IOITransType"
                                                        "106" "Issuer"
                                                        "29" "LastCapacity"
                                                        "195" "LastForwardPoints"
                                                        "30" "LastMkt"
                                                        "369" "LastMsgSeqNumProcessed"
                                                        "31" "LastPx"
                                                        "32" "LastShares"
                                                        "194" "LastSpotRate"
                                                        "151" "LeavesQty"
                                                        "33" "LinesOfText"
                                                        "409" "LiquidityIndType"
                                                        "441" "LiquidityNumSecurities"
                                                        "403" "LiquidityPctHigh"
                                                        "402" "LiquidityPctLow"
                                                        "404" "LiquidityValue"
                                                        "69" "ListExecInst"
                                                        "433" "ListExecInstType"
                                                        "66" "ListID"
                                                        "392" "ListName"
                                                        "431" "ListOrderStatus"
                                                        "67" "ListSeqNo"
                                                        "444" "ListStatusText"
                                                        "429" "ListStatusType"
                                                        "114" "LocateReqd"
                                                        "283" "LocationID"
                                                        "333" "LowPx"
                                                        "264" "MarketDepth"
                                                        "205" "MaturityDay"
                                                        "200" "MaturityMonthYear"
                                                        "111" "MaxFloor"
                                                        "383" "MaxMessageSize"
                                                        "210" "MaxShow"
                                                        "288" "MDEntryBuyer"
                                                        "272" "MDEntryDate"
                                                        "278" "MDEntryID"
                                                        "282" "MDEntryOriginator"
                                                        "290" "MDEntryPositionNo"
                                                        "270" "MDEntryPx"
                                                        "280" "MDEntryRefID"
                                                        "289" "MDEntrySeller"
                                                        "271" "MDEntrySize"
                                                        "273" "MDEntryTime"
                                                        "269" "MDEntryType"
                                                        "275" "MDMkt"
                                                        "262" "MDReqID"
                                                        "281" "MDReqRejReason"
                                                        "279" "MDUpdateAction"
                                                        "265" "MDUpdateType"
                                                        "347" "MessageEncoding"
                                                        "110" "MinQty"
                                                        "137" "MiscFeeAmt"
                                                        "138" "MiscFeeCurr"
                                                        "139" "MiscFeeType"
                                                        "385" "MsgDirection"
                                                        "34" "MsgSeqNum"
                                                        "35" "MsgType"
                                                        "442" "MultiLegReportingType"
                                                        "430" "NetGrossInd"
                                                        "118" "NetMoney"
                                                        "36" "NewSeqNo"
                                                        "78" "NoAllocs"
                                                        "420" "NoBidComponents"
                                                        "398" "NoBidDescriptors"
                                                        "382" "NoContraBrokers"
                                                        "85" "NoDlvyInst"
                                                        "124" "NoExecs"
                                                        "199" "NoIOIQualifiers"
                                                        "268" "NoMDEntries"
                                                        "267" "NoMDEntryTypes"
                                                        "136" "NoMiscFees"
                                                        "384" "NoMsgTypes"
                                                        "73" "NoOrders"
                                                        "295" "NoQuoteEntries"
                                                        "296" "NoQuoteSets"
                                                        "146" "NoRelatedSym"
                                                        "215" "NoRoutingIDs"
                                                        "82" "NoRpts"
                                                        "428" "NoStrikes"
                                                        "208" "NotifyBrokerOfCredit"
                                                        "386" "NoTradingSessions"
                                                        "346" "NumberOfOrders"
                                                        "417" "NumBidders"
                                                        "157" "NumDaysInterest"
                                                        "395" "NumTickets"
                                                        "191" "OfferForwardPoints"
                                                        "133" "OfferPx"
                                                        "135" "OfferSize"
                                                        "190" "OfferSpotRate"
                                                        "115" "OnBehalfOfCompID"
                                                        "144" "OnBehalfOfLocationID"
                                                        "370" "OnBehalfOfSendingTime"
                                                        "116" "OnBehalfOfSubID"
                                                        "77" "OpenClose"
                                                        "286" "OpenCloseSettleFlag"
                                                        "206" "OptAttribute"
                                                        "37" "OrderID"
                                                        "38" "OrderQty"
                                                        "192" "OrderQty2"
                                                        "103" "OrdRejReason"
                                                        "39" "OrdStatus"
                                                        "40" "OrdType"
                                                        "41" "OrigClOrdID"
                                                        "122" "OrigSendingTime"
                                                        "42" "OrigTime"
                                                        "412" "OutMainCntryUIndex"
                                                        "407" "OutsideIndexPct"
                                                        "211" "PegDifference"
                                                        "43" "PossDupFlag"
                                                        "97" "PossResend"
                                                        "140" "PrevClosePx"
                                                        "44" "Price"
                                                        "423" "PriceType"
                                                        "81" "ProcessCode"
                                                        "415" "ProgPeriodInterval"
                                                        "414" "ProgRptReqs"
                                                        "201" "PutOrCall"
                                                        "297" "QuoteAckStatus"
                                                        "298" "QuoteCancelType"
                                                        "276" "QuoteCondition"
                                                        "299" "QuoteEntryID"
                                                        "368" "QuoteEntryRejectReason"
                                                        "117" "QuoteID"
                                                        "300" "QuoteRejectReason"
                                                        "131" "QuoteReqID"
                                                        "303" "QuoteRequestType"
                                                        "301" "QuoteResponseLevel"
                                                        "302" "QuoteSetID"
                                                        "367" "QuoteSetValidUntilTime"
                                                        "319" "RatioQty"
                                                        "96" "RawData"
                                                        "95" "RawDataLength"
                                                        "72" "RefAllocID"
                                                        "372" "RefMsgType"
                                                        "45" "RefSeqNum"
                                                        "371" "RefTagID"
                                                        "46" "RelatdSym"
                                                        "113" "ReportToExch"
                                                        "141" "ResetSeqNumFlag"
                                                        "217" "RoutingID"
                                                        "216" "RoutingType"
                                                        "83" "RptSeq"
                                                        "47" "Rule80A"
                                                        "198" "SecondaryOrderID"
                                                        "91" "SecureData"
                                                        "90" "SecureDataLen"
                                                        "107" "SecurityDesc"
                                                        "207" "SecurityExchange"
                                                        "48" "SecurityID"
                                                        "320" "SecurityReqID"
                                                        "321" "SecurityRequestType"
                                                        "322" "SecurityResponseID"
                                                        "323" "SecurityResponseType"
                                                        "179" "SecuritySettlAgentAcctName"
                                                        "178" "SecuritySettlAgentAcctNum"
                                                        "177" "SecuritySettlAgentCode"
                                                        "180" "SecuritySettlAgentContactName"
                                                        "181" "SecuritySettlAgentContactPhone"
                                                        "176" "SecuritySettlAgentName"
                                                        "324" "SecurityStatusReqID"
                                                        "326" "SecurityTradingStatus"
                                                        "167" "SecurityType"
                                                        "287" "SellerDays"
                                                        "331" "SellVolume"
                                                        "49" "SenderCompID"
                                                        "142" "SenderLocationID"
                                                        "50" "SenderSubID"
                                                        "51" "SendingDate"
                                                        "52" "SendingTime"
                                                        "373" "SessionRejectReason"
                                                        "174" "SettlBrkrCode"
                                                        "119" "SettlCurrAmt"
                                                        "120" "SettlCurrency"
                                                        "155" "SettlCurrFxRate"
                                                        "156" "SettlCurrFxRateCalc"
                                                        "172" "SettlDeliveryType"
                                                        "173" "SettlDepositoryCode"
                                                        "175" "SettlInstCode"
                                                        "162" "SettlInstID"
                                                        "160" "SettlInstMode"
                                                        "214" "SettlInstRefID"
                                                        "165" "SettlInstSource"
                                                        "163" "SettlInstTransType"
                                                        "166" "SettlLocation"
                                                        "63" "SettlmntTyp"
                                                        "53" "Shares"
                                                        "54" "Side"
                                                        "396" "SideValue1"
                                                        "397" "SideValue2"
                                                        "401" "SideValueInd"
                                                        "89" "Signature"
                                                        "93" "SignatureLength"
                                                        "377" "SolicitedFlag"
                                                        "218" "SpreadToBenchmark"
                                                        "171" "StandInstDbID"
                                                        "170" "StandInstDbName"
                                                        "169" "StandInstDbType"
                                                        "99" "StopPx"
                                                        "202" "StrikePrice"
                                                        "443" "StrikeTime"
                                                        "147" "Subject"
                                                        "263" "SubscriptionRequestType"
                                                        "55" "Symbol"
                                                        "65" "SymbolSfx"
                                                        "56" "TargetCompID"
                                                        "143" "TargetLocationID"
                                                        "57" "TargetSubID"
                                                        "112" "TestReqID"
                                                        "58" "Text"
                                                        "274" "TickDirection"
                                                        "59" "TimeInForce"
                                                        "393" "TotalNumSecurities"
                                                        "387" "TotalVolumeTraded"
                                                        "68" "TotNoOrders"
                                                        "422" "TotNoStrikes"
                                                        "304" "TotQuoteEntries"
                                                        "277" "TradeCondition"
                                                        "75" "TradeDate"
                                                        "418" "TradeType"
                                                        "336" "TradingSessionID"
                                                        "344" "TradSesCloseTime"
                                                        "345" "TradSesEndTime"
                                                        "338" "TradSesMethod"
                                                        "339" "TradSesMode"
                                                        "342" "TradSesOpenTime"
                                                        "343" "TradSesPreCloseTime"
                                                        "335" "TradSesReqID"
                                                        "341" "TradSesStartTime"
                                                        "340" "TradSesStatus"
                                                        "60" "TransactTime"
                                                        "436" "UnderlyingContractMultiplier"
                                                        "435" "UnderlyingCouponRate"
                                                        "318" "UnderlyingCurrency"
                                                        "305" "UnderlyingIDSource"
                                                        "306" "UnderlyingIssuer"
                                                        "314" "UnderlyingMaturityDay"
                                                        "313" "UnderlyingMaturityMonthYear"
                                                        "317" "UnderlyingOptAttribute"
                                                        "315" "UnderlyingPutOrCall"
                                                        "307" "UnderlyingSecurityDesc"
                                                        "308" "UnderlyingSecurityExchange"
                                                        "309" "UnderlyingSecurityID"
                                                        "310" "UnderlyingSecurityType"
                                                        "316" "UnderlyingStrikePrice"
                                                        "311" "UnderlyingSymbol"
                                                        "312" "UnderlyingSymbolSfx"
                                                        "325" "UnsolicitedIndicator"
                                                        "61" "Urgency"
                                                        "149" "URLLink"
                                                        "62" "ValidUntilTime"
                                                        "408" "ValueOfFutures"
                                                        "105" "WaveNo"
                                                        "410" "WtAverageLiquidity"
                                                        "213" "XmlData"
                                                        "212" "XmlDataLen"
                                                        "6000" "DiscretionUsedSw"
                                                        )))

(setq enums-hash #s(hash-table test equal size 100 data (
                                                         ( "35" . "0")  "Heartbeat"
                                                         ( "35" . "1")  "Test Request"
                                                         ( "35" . "2")  "Resend Request"
                                                         ( "35" . "3")  "Reject"
                                                         ( "35" . "4")  "Sequence Reset"
                                                         ( "35" . "5")  "Logout"
                                                         ( "35" . "6")  "Indication of Interest"
                                                         ( "35" . "7")  "Advertisement"
                                                         ( "35" . "8")  "Execution Report"
                                                         ( "35" . "9")  "Order Cancel Reject"
                                                         ( "35" . "A")  "Logon"
                                                         ( "35" . "B")  "News"
                                                         ( "35" . "C")  "Email"
                                                         ( "35" . "D")  "Order - Single"
                                                         ( "35" . "E")  "Order - List"
                                                         ( "35" . "F")  "Order Cancel Request"
                                                         ( "35" . "G")  "Order Cancel/Replace Request"
                                                         ( "35" . "H")  "Order Status Request"
                                                         ( "35" . "J")  "Allocation"
                                                         ( "35" . "K")  "List Cancel Request"
                                                         ( "35" . "L")  "List Execute"
                                                         ( "35" . "M")  "List Status Request"
                                                         ( "35" . "N")  "List Status"
                                                         ( "35" . "P")  "Allocation ACK"
                                                         ( "35" . "Q")  "Don't Know Trade"
                                                         ( "35" . "R")  "Quote Request"
                                                         ( "35" . "S")  "Quote"
                                                         ( "35" . "T")  "Settlement Instructions"
                                                         ( "35" . "V")  "Market Data Request"
                                                         ( "35" . "W")  "Market Data-Snapshot/Full Refresh"
                                                         ( "35" . "X")  "Market Data-Incremental Refresh"
                                                         ( "35" . "Y")  "Market Data Request Reject"
                                                         ( "35" . "Z")  "Quote Cancel"
                                                         ( "35" . "a")  "Quote Status Request"
                                                         ( "35" . "b")  "Quote Acknowledgement"
                                                         ( "35" . "c")  "Security Definition Request"
                                                         ( "35" . "d")  "Security Definition"
                                                         ( "35" . "e")  "Security Status Request"
                                                         ( "35" . "f")  "Security Status"
                                                         ( "35" . "g")  "Trading Session Status Request"
                                                         ( "35" . "h")  "Trading Session Status"
                                                         ( "35" . "i")  "Mass Quote"
                                                         ( "35" . "j")  "Business Message Reject"
                                                         ( "35" . "k")  "Bid Request"
                                                         ( "35" . "l")  "Bid Response"
                                                         ( "35" . "m")  "List Strike Price"
                                                         ("150" . "0")  "New"
                                                         ("150" . "1")  "Partial fill"
                                                         ("150" . "2")  "Fill"
                                                         ("150" . "3")  "Done for day"
                                                         ("150" . "4")  "Canceled"
                                                         ("150" . "5")  "Replace"
                                                         ("150" . "6")  "Pending Cancel"
                                                         ("150" . "7")  "Stopped"
                                                         ("150" . "8")  "Rejected"
                                                         ("150" . "9")  "Suspended"
                                                         ("150" . "A")  "Pending New"
                                                         ("150" . "B")  "Calculated"
                                                         ("150" . "C")  "Expired"
                                                         ("150" . "D")  "Restated"
                                                         ("150" . "E")  "Pending Replace"
                                                         ("20" ."0")  "New"
                                                         ("20" ."1")  "Cancel"
                                                         ("20" ."2")  "Correct"
                                                         ("20" ."3")  "Status"

                                                         ("22" . "1") "CUSIP"
                                                         ("22" . "2") "SEDOL"
                                                         ("22" . "3") "QUIK"
                                                         ("22" . "4") "ISIN number"
                                                         ("22" . "5") "RIC code"
                                                         ("22" . "6") "ISO Currency <15> Code"
                                                         ("22" . "7") "ISO Country <421> Code"
                                                         ("22" . "8") "Exchange Symbol <55>"
                                                         ("22" . "9") "Consolidated Tape Association (CTA) Symbol <55> (SIAC CTS/CQS line format)"
                                                         ("22" . "A") "Bloomberg Symbol <55>"
                                                         ("22" . "B") "Wertpapier"
                                                         ("22" . "C") "Dutch"
                                                         ("22" . "D") "Valoren"
                                                         ("22" . "E") "Sicovam"
                                                         ("22" . "F") "Belgian"
                                                         ("22" . "G") "Common (Clearstream and Euroclear)"
                                                         ("22" . "H") "Clearing House / Clearing Organization"
                                                         ("22" . "I") "ISDA/FpML Product <460> Specification"
                                                         ("22" . "J") "Options Price <44> Reporting Authority"


                                                         ("18" . "1")  "Not held"
                                                         ("18" . "2")  "Work"
                                                         ("18" . "3")  "Go along"
                                                         ("18" . "4")  "Over the day"
                                                         ("18" . "5")  "Held"
                                                         ("18" . "6")  "Participate don't initiate"
                                                         ("18" . "7")  "Strict scale"
                                                         ("18" . "8")  "Try to scale"
                                                         ("18" . "9")  "Stay on bidside"
                                                         ("18" . "0")  "Stay on offerside"
                                                         ("18" . "A")  "No cross (cross is forbidden)"
                                                         ("18" . "B")  "OK to cross"
                                                         ("18" . "C")  "Call first"
                                                         ("18" . "D")  "Percent of volume '(indicates that the sender does not want to be all of the volume on the floor vs. a specific percentage)'"
                                                         ("18" . "E")  "Do not increase - DNI"
                                                         ("18" . "F")  "Do not reduce - DNR"
                                                         ("18" . "G")  "All or none - AON"
                                                         ("18" . "I")  "Institutions only"
                                                         ("18" . "L")  "Last peg (last sale)"
                                                         ("18" . "M")  "Mid-price peg (midprice of inside quote)"
                                                         ("18" . "N")  "Non-negotiable"
                                                         ("18" . "O")  "Opening peg"
                                                         ("18" . "P")  "Market peg"
                                                         ("18" . "R")  "Primary peg (primary market - buy at bid/sell at offer)"
                                                         ("18" . "S")  "Suspend"
                                                         ("18" . "T")  "Fixed Peg to Local best bid or offer at time of order"
                                                         ("18" . "U")  "Customer Display Instruction (Rule11Ac1-1/4)"
                                                         ("18" . "V")  "Netting (for Forex)"
                                                         ("18" . "W")  "Peg to VWAP"
                                                         ("39" . "0")  "New"
                                                         ("39" . "1")  "Partially filled"
                                                         ("39" . "2")  "Filled"
                                                         ("39" . "3")  "Done for day"
                                                         ("39" . "4")  "Canceled"
                                                         ("39" . "5")  "Replaced"
                                                         ("39" . "6")  "Pending Cancel (e.g. result of Order Cancel Request <F>)"
                                                         ("39" . "7")  "Stopped"
                                                         ("39" . "8")  "Rejected"
                                                         ("39" . "9")  "Suspended"
                                                         ("39" . "A")  "Pending New"
                                                         ("39" . "B")  "Calculated"
                                                         ("39" . "C")  "Expired"
                                                         ("39" . "D")  "Accepted for bidding"
                                                         ("39" . "E")  "Pending Replace (e.g. result of Order Cancel/Replace Request <G>)"
                                                         ("40" . "1")  "Market"
                                                         ("40" . "2")  "Limit"
                                                         ("40" . "3")  "Stop"
                                                         ("40" . "4")  "Stop limit"
                                                         ("40" . "5")  "Market on close"
                                                         ("40" . "6")  "With or without"
                                                         ("40" . "7")  "Limit or better"
                                                         ("40" . "8")  "Limit with or without"
                                                         ("40" . "9")  "On basis"
                                                         ("40" . "A")  "On close"
                                                         ("40" . "B")  "Limit on close"
                                                         ("40" . "C")  "Forex - Market"
                                                         ("40" . "D")  "Previously quoted"
                                                         ("40" . "E")  "Previously indicated"
                                                         ("40" . "F")  "Forex - Limit"
                                                         ("40" . "G")  "Forex - Swap"
                                                         ("40" . "H")  "Forex - Previously Quoted"
                                                         ("40" . "I")  "Funari (Limit Day Order with unexecuted portion handled as Market On Close. e.g. Japan)"
                                                         ("40" . "P")  "Pegged"
                                                         ("54" . "1")  "Buy"
                                                         ("54" . "2")  "Sell"
                                                         ("54" . "3")  "Buy minus"
                                                         ("54" . "4")  "Sell plus"
                                                         ("54" . "5")  "Sell short"
                                                         ("54" . "6")  "Sell short exempt"
                                                         ("54" . "7")  "Undisclosed (valid for IOI and List Order messages only)"
                                                         ("54" . "8")  "Cross (orders where counterparty is an exchange, valid for all messages except IOIs)"
                                                         ("54" . "9")  "Cross short"
                                                         ("59" . "0")  "Day"
                                                         ("59" . "1")  "Good Till Cancel (GTC)"
                                                         ("59" . "2")  "At the Opening (OPG)"
                                                         ("59" . "3")  "Immediate or Cancel (IOC)"
                                                         ("59" . "4")  "Fill or Kill (FOK)"
                                                         ("59" . "5")  "Good Till Crossing (GTX)"
                                                         ("59" . "6")  "Good Till Date"
                                                         ("103" . "0")  "Broker option"
                                                         ("103" . "1")  "Unknown symbol"
                                                         ("103" . "2")  "Exchange closed"
                                                         ("103" . "3")  "Order exceeds limit"
                                                         ("103" . "4")  "Too late to enter"
                                                         ("103" . "5")  "Unknown Order"
                                                         ("103" . "6")  "Duplicate Order (e.g. dupe ClOrdID <11>)"
                                                         ("103" . "7")  "Duplicate of a verbally communicated order"
                                                         ("103" . "8")  "Stale Order"
                                                         ("102" . "0")  "Too late to cancel"
                                                         ("102" . "1")  "Unknown order"
                                                         ("102" . "2")  "Broker Option"
                                                         ("102" . "3")  "Order already in Pending Cancel or Pending Replace status"
                                                         ("167" . "BA")   "Bankers Acceptance"
                                                         ("167" . "CB")   "Convertible Bond (Note not part of ISITC spec)"
                                                         ("167" . "CD")   "Certificate Of Deposit"
                                                         ("167" . "CMO")   "Collateralize Mortgage Obligation"
                                                         ("167" . "CORP")   "Corporate Bond"
                                                         ("167" . "CP")   "Commercial Paper"
                                                         ("167" . "CPP")   "Corporate Private Placement"
                                                         ("167" . "CS")   "Common Stock"
                                                         ("167" . "FHA")   "Federal Housing Authority"
                                                         ("167" . "FHL")   "Federal Home Loan"
                                                         ("167" . "FN")   "Federal National Mortgage Association"
                                                         ("167" . "FOR")   "Foreign Exchange Contract"
                                                         ("167" . "FUT")   "Future"
                                                         ("167" . "GN")   "Government National Mortgage Association"
                                                         ("167" . "GOVT")   "Treasuries + Agency Debenture"
                                                         ("167" . "IET")  "Mortgage IOETTE"
                                                         ("167" . "MF")   "Mutual Fund"
                                                         ("167" . "MIO")   "Mortgage Interest Only"
                                                         ("167" . "MPO")   "Mortgage Principal Only"
                                                         ("167" . "MPP")   "Mortgage Private Placement"
                                                         ("167" . "MPT")   "Miscellaneous Pass-Thru"
                                                         ("167" . "MUNI")   "Municipal Bond"
                                                         ("167" . "NONE")   "No ISITC Security Type"
                                                         ("167" . "OPT")   "Option"
                                                         ("167" . "PS")   "Preferred Stock"
                                                         ("167" . "RP")   "Repurchase Agreement"
                                                         ("167" . "RVRP")   "Reverse Repurchase Agreement"
                                                         ("167" . "SL")   "Student Loan Marketing Association"
                                                         ("167" . "TD")   "Time Deposit"
                                                         ("167" . "USTB")   "US Treasury Bill"
                                                         ("167" . "WAR")   "Warrant"
                                                         ("167" . "ZOO")   "Cats, Tigers & Lions (a real code: US Treasury Receipts)"
                                                         ("87" . "0") "accepted (successfully processed)"
                                                         ("87" . "1") "block level reject"
                                                         ("87" . "2") "account level reject"
                                                         ("87" . "3") "received (received, not yet processed)"
                                                         ("87" . "4") "incomplete"
                                                         ("87" . "5") "rejected by intermediary"



                                                         ("452" . "1") "Executing Firm (formerly FIX 4.2 ExecBroker <76>)"
                                                         ("452" . "2") "Broker of Credit (formerly FIX 4.2 BrokerOfCredit <92>)"
                                                         ("452" . "3") "Client ID (formerly FIX 4.2 ClientID <109>)"
                                                         ("452" . "4") "Clearing Firm (formerly FIX 4.2 ClearingFirm <439>)"
                                                         ("452" . "5") "Investor ID"
                                                         ("452" . "6") "Introducing Firm"
                                                         ("452" . "7") "Entering Firm"
                                                         ("452" . "8") "Locate/Lending Firm (for short-sales)"
                                                         ("452" . "9") "Fund manager Client ID (for CIV)"
                                                         ("452" . "0") "Settlement Location (formerly FIX 4.2 SettlLocation <166>)"
                                                         ("452" . "1") "Order Origination Trader (associated with Order Origination Firm - e.g. trader who initiates/submits the order)"
                                                         ("452" . "2") "Executing Trader (associated with Executing Firm - actually executes)"
                                                         ("452" . "3") "Order Origination Firm (e.g. buyside firm)"
                                                         ("452" . "4") "Giveup Clearing Firm (firm to which trade is given up)"
                                                         ("452" . "5") "Correspondant Clearing Firm"
                                                         ("452" . "6") "Executing System"
                                                         ("452" . "7") "Contra Firm"
                                                         ("452" . "8") "Contra Clearing Firm"
                                                         ("452" . "9") "Sponsoring Firm"
                                                         ("452" . "20") "Underlying Contra Firm"
                                                         ("452" . "2") "Clearing Organization"
                                                         ("452" . "22") "Exchange"
                                                         ("452" . "24") "Customer Account <1>"
                                                         ("452" . "25") "Correspondent Clearing Organization"
                                                         ("452" . "26") "Correspondent Broker"
                                                         ("452" . "27") "Buyer/Seller (Receiver/Deliverer)"
                                                         ("452" . "28") "Custodian"
                                                         ("452" . "29") "Intermediary"
                                                         ("452" . "30") "Agent"
                                                         ("452" . "3") "Sub custodian"
                                                         ("452" . "32") "Beneficiary"
                                                         ("452" . "33") "Interested party"
                                                         ("452" . "34") "Regulatory body"
                                                         ("452" . "35") "Liquidity provider"
                                                         ("452" . "36") "Entering Trader"
                                                         ("452" . "37") "Contra Trader"
                                                         ("452" . "38") "Position Account <1>"


                                                         ("456" . "1") "CUSIP"
                                                         ("456" . "2") "SEDOL"
                                                         ("456" . "3") "QUIK"
                                                         ("456" . "4") "ISIN number"
                                                         ("456" . "5") "RIC code"
                                                         ("456" . "6") "ISO Currency <15> Code"
                                                         ("456" . "7") "ISO Country <421> Code"
                                                         ("456" . "8") "Exchange Symbol <55>"
                                                         ("456" . "9") "Consolidated Tape Association (CTA) Symbol <55> (SIAC CTS/CQS line format)"
                                                         ("456" . "A") "Bloomberg Symbol <55>"
                                                         ("456" . "B") "Wertpapier"
                                                         ("456" . "C") "Dutch"
                                                         ("456" . "D") "Valoren"
                                                         ("456" . "E") "Sicovam"
                                                         ("456" . "F") "Belgian"
                                                         ("456" . "G") "Common (Clearstream and Euroclear)"
                                                         ("456" . "H") "Clearing House / Clearing Organization"
                                                         ("456" . "I") "ISDA/FpML Product <460> Specification"
                                                         ("456" . "J") "Options Price <44> Reporting Authority"

                                                         ( "447" . "B") "BIC (Bank Identification Code—Swift managed) code (ISO 9362)"
                                                         ( "447" . "C") "Generally accepted market participant identifier (e.g. NASD mnemonic)"
                                                         ( "447" . "D") "Proprietary/Custom code"
                                                         ( "447" . "E") "ISO Country <421> Code"
                                                         ( "447" . "F") "Settlement Entity Location"
                                                         ( "447" . "G") "MIC (ISO 0383 - Market Identifier Code)"
                                                         ( "447" . "H") "CSD participant/member code (e.g. Euroclear, DTC, CREST or Kassenverein number)"
                                                         ( "447" . "1") "Korean Investor ID"
                                                         ( "447" . "2") "Taiwanese Qualified Foreign Investor ID QFII / FID"
                                                         ( "447" . "3") "Taiwanese Trading Account <1>"
                                                         ( "447" . "4") "Malaysian Central Depository (MCD) number"
                                                         ( "447" . "5") "Chinese B Share (Shezhen and Shanghai)"
                                                         ( "447" . "6") "UK National Insurance or Pension Number"
                                                         ( "447" . "7") "US Social Security Number"
                                                         ( "447" . "8") "US Employer Identification Number"
                                                         ( "447" . "9") "Australian Business Number"
                                                         ( "447" . "A") "Australian Tax File Number"
                                                         )))
